### ISSUE TITLE
Changing link and code colour

### ISSUE THREAD

**Issue by EllaKaye** [EmilHvitfeldt/quarto-revealjs-inverse#1]
Hi Emil,

Thank you for this template! The inverse class is the thing I miss most from xaringan, and this shows how to fill that gap. 

I'm trying to adapt the template to make an extension for presentations with my university's brand colours and I'm getting stuck changing link colours and regular code (i.e. text between ` `` ` marks rather than in code blocks and outputs). 

I have `$link-color` and `$code-color` set earlier in my scss file and want to be able to update them in the `.inverse` class, but redefining them there doesn't work.

Inspecting the code element suggests these are `.reveal code`, but setting css for those inside the `.inverse` class in the `inverse.scss` template doesn't seem to change them either. Similarly, links seems to be `.reveal a`, and I also can't seem to change those.

Do you have any suggestions?

Thanks!

**Comment by EmilHvitfeldt** [comment]
Hello @EllaKaye 👋 

I updated the template to include inline code styling and linking: https://github.com/EmilHvitfeldt/quarto-revealjs-inverse/commit/55e4509b687f2203577f6bd929037d5606e918e5

https://emilhvitfeldt.github.io/quarto-revealjs-inverse/#/quarto-1

you want to do something like this:

```
.inverse {
  color: #d6d6d6;
  h1, h2, h3 {
    color: #f3f3f3;
  }

  a {
    color: #00e0e0;
  }

  p code {
    color: #ffd700;
  }

  ... more rules
}
```

here `a` is your link color inside `.inverse` and `p code` in the inline code

<img width="1626" alt="Screen Shot 2023-03-28 at 11 53 05 AM" src="https://user-images.githubusercontent.com/14034784/228338912-fe3a3b02-5968-4627-af2a-6e4624ecf135.png">

**Comment by EllaKaye** [comment]
Thanks Emil for making that change so quickly. Now I see it, the solution looks so obvious that I can't believe I missed it 🤦‍♀️

**Comment by EmilHvitfeldt** [comment]
no problem, I went a roundabout way to get to that solution 😄
